[package]
name = "function_study"
version = "0.1.0"
authors = ["Gustavo Freire Santos <gustavo.freire.s@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
